HUGGINGFACE_TOKEN: "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"
IEMOCAP_DIR: C:/Users/admin/Documents/GNN_SER/Data/IEMOCAP/
EXECUTE_OPENSMILE: C:/Users/admin/Documents/GNN_SER/opensmile-3.0.2/bin/SMILExtract.ex
OPENSMILE_CONFIG: C:/Users/admin/Documents/GNN_SER/opensmile-3.0.2/config/chroma/chroma_fft.conf


database:
  host: localhost
  password: secret
  port: 5432
  username: admin
features:
  enable_feature_x: true
  enable_feature_y: false
logging:
  file: /var/log/app.log
  level: INFO
server:
  host: 0.0.0.0
  port: 8080
